sudo: false
dist: trusty
language: php
cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files

branches:
  only:
  - master
  - develop

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  # Install nvm for nodejs
  - nvm install 8.7.0
  - nvm use 8.7.0
  # Install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  # Install dependencies and build the project
  - make yarn
  - make composerinstalldev
  - make build

script:
  - make runtests
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
