sudo: false
dist: trusty
language: php
cache:
    directories:
        - $HOME/.composer/cache/files

branches:
  only:
  - master
  - develop

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  # Install nvm for nodejs
  - nvm install 4.3.0
  - nvm use 4.3.0
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add gulp
  # Install dependencies and build the project
  - make yarn
  - make composerinstalldev
  - make build

script:
  - make runtests
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
